-- AlterTable
ALTER TABLE "Lead" ALTER COLUMN "arr" DROP DEFAULT,
ALTER COLUMN "employees" DROP DEFAULT,
ALTER COLUMN "needs" DROP DEFAULT,
ALTER COLUMN "phone" DROP DEFAULT,
ALTER COLUMN "sector" DROP DEFAULT;
